### PR TITLE
feat(20): add lambda image

### PR DESCRIPTION
**Pull request by mloberg**
Add pull request template to make sure all the new image things are done (mostly README, which I forgot about initially)

### CODE REVIEW

**Review by Dbaker1298 — DISMISSED** [review]

**Review by juniormince — COMMENTED** [review]
Is this different from [this base image](https://github.com/articulate/docker-node/blob/main/20/base/Dockerfile) that was added?

**Comment by juniormince** [comment]
Or sorry that's vague I mean is it replacing that other node-20 image or are they for different purposes, haven't dug into it just saw 20 already existed

**Comment by juniormince** [comment]
Oh just kidding just kidding my eyes skimmed over "lambda" because I was trying to comment quickly before investigating too much and was confused by the change in dir/ formatting with 20 so I wanted to ask before it got merged. Looks good! Only other question:

- Is the `DL3041` warning happening because there's no version specified on shadow-utils, or what's up with that? I know it's only a warning but just curious

**Review by juniormince — APPROVED** [review]

**Comment by mloberg** [comment]
@juniormince The new ignore is for dnf. Each package manager must have their own number and since we're adding dnf for lambda, we need to add that ignore

**Review by Dbaker1298 — APPROVED** [review]

**Pull request merged**
